Mvc5FrameWorkProject/MvcEf5/MvcEf5/Areas/Master/Controllers/MainMasterController.cs
using MvcEf5.Controllers;
using MvcEf5.Filter;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcEf5.Areas.Master.Controllers
{
    [SupportFilterAttribute]
    public class MainMasterController : BaseController
    {
        //
        // GET: /Master/MainMaster/
        public ActionResult Index()
        {
            return View();
        }
    }
}

Mvc5FrameWorkProject/MvcEf5/MvcEf5/Areas/Mobile/Controllers/WechatController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcEf5.Areas.Mobile.Controllers
{
    public class WechatController : Controller
    {
        //
        // GET: /Mobile/Wechat/
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult GotoPc()
        {
            var urldefault = "~/pc/Windowspc/index";
            //var urldefault = Url.Action("index", "windowspc", new { area = "" });
            return Redirect(urldefault);
        }
    }
}

Mvc5FrameWorkProject/MvcEf5/MvcEf5/Controllers/DemoController.cs
using Services.Bll;
using Services.IBll;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcEf5.Controllers
{
    public class DemoController : Controller
    {
        IUserServices _userServices;

        public DemoController()
        {
            _userServices = new UserServices();
        }

        //
        // GET: /Demo/
        public ActionResult Index()
        {
            var model = _userServices.getAlluser();
            return View(model);
        }

        public ActionResult Edit()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Edit(FormCollection entities)
        {

            return View();
        }

        public JsonResult Index2(string d)
        {
            return Json(new { success = "成功", message = d }, JsonRequestBehavior.AllowGet);
        }
	}
}

Mvc5FrameWorkProject/MvcEf5/MvcEf5/Controllers/HomeController.cs
using Enums;
using Models;
using MvcEf5.Filter;
using Newtonsoft.Json;
using Response;
using Response.Redis;
using Services.Bll;
using Services.IBll;
using StackExchange.Redis;
using System;
using System.Collections.Generic;
using System.Data.Common;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Web.Mvc;

namespace MvcEf5.Controllers
{
    //[SupportFilterAttribute]   //验证权限
    public class HomeController : BaseController
    {
        IUserServices _userServices;
        IRedisService _redisService;
        public HomeController()
        {
            _userServices = new UserServices();
            _redisService = new RedisService();
            _redisService.SaveInRedis();
        }

        #region 错误处理
        /// <summary>
        /// 第一种错误处理机制，控制器继承自BaseController
        /// 如果页面出错跳转到错误页面  BaseController 中  自动使用basecontroller中的错误处理逻辑 
        /// 因为继承了 BaseController 控制器
        /// </summary>
        /// <returns></returns>
        public ActionResult ErrorIndex()
        {
            //List<Users> model = RedisHelper.HashGetAll<Users>("Users");
            //return View("Index");
            throw new Exception("This is Test Error");
        }
        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public ActionResult ErrorIndex2()
        {
            var a = "11";
            var b = "ddddd";
            var c = int.Parse(a) + int.Parse(b);
            return View("Index");
        }
        #endregion

        public ActionResult Index()
        {
            List<Users> model = RedisHelper.HashGetAll<Users>("Users");
            return View(model);
        }

        #region session clear
        /// <summary>
        /// 清理掉session 验证控制器的是否已登录的权限验证
        /// </summary>
        /// <returns></returns>
        public ActionResult Clear()
        {
            WebSession.SessionClear();
            return RedirectToAction("Index", "Home");
        }

        #endregion

        #region 编辑以及保存
        public ActionResult Edit(string N, int id)
        {
            EntitiesNames en = new EntitiesNames();
            N = getClassNames<EntitiesNames>(N, en);
            if (N != "")
            {
                var model = RedisHelper.GetHashKey<Users>(N, N + "-Id-" + id.ToString());
                return View(model);
            }
            else
            {
                return RedirectToAction("Index", "Error");
            }
        }
        /// <summary>
        /// 修改操作，不仅修改数据库中的数据值，还需要修改存储在redis中的数据值
        /// </summary>
        /// <param name="entity"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Edit(FormCollection entity)
        {

            Users u = _userServices.GetUserById(int.Parse(entity.GetValue("id").AttemptedValue)); //new Users();
            //u.id = int.Parse(entity.GetValue("id").AttemptedValue);
            u.username = entity.GetValue("username").AttemptedValue;
            u.isdelete = entity.GetValue("isdelete") == null ? false : true;  // .AttemptedValue == "on" ? true : false;
            u.roleid = int.Parse(entity.GetValue("roleid").AttemptedValue);
            _userServices.UpdateUser(u);

            return RedirectToAction("Index");
        }
        #endregion

        #region 公共删除方法
        public ActionResult CommonDel(string N, int id)
        {
            EntitiesNames en = new EntitiesNames();
            var currClassname = getClassNames<EntitiesNames>(N, en, 0);  //这里获取了类的名称，将返回值修改为返回类名         
            Assembly[] AssbyCustmList = System.AppDomain.CurrentDomain.GetAssemblies();//查找所有的程序集
            foreach (Assembly item in AssbyCustmList)
            {
                var b = item.FullName;
                var e = item.GetType();
                var f = item.GetTypes();
                var g = item.Modules;
                var h = item.GetManifestResourceNames();
                var items = item.GetTypes().Where(a => a.Name == "Users").FirstOrDefault(); //程序集里面的对象
                if (items != null)
                {
                    var c = item.GetTypes().Where(a => a.Name == "Users");
                    var d = item.CreateInstance("Models.Users");
                }
            }
            string assemblyname = "";
            Assembly.LoadFrom(assemblyname);

            //_userServices.DeleteUser(id);
            return View();
        }


        public ActionResult a()
        {
            DbResponse _db = new DbResponse();
            var d = _db.Users.Where(a => a.username.Contains("l")).Sum(e => e.id);
            var dddd = _db.Database.Log;
            //try
            //{
            //    var psql = d.GetType().GetMethod("ToTraceString").Invoke(d, null);
            //}
            //catch
            //{ }
            //var c = d;
            return null;
        }
        #endregion

        #region
        public ActionResult Del(int id)
        {
            _userServices.DeleteUser(id);
            return View();
        }
        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
        #endregion



        public ActionResult Tolist()
        {
            using (var _db = new Dbresponse2())
            {
                var cona = (from a in _db.Users
                             where a.username.Contains("l")
                             select a).AsEnumerable();

                //var cona = _db.Users.Where(a => a.username.Contains("l")).ToList();

                var conb = cona.Count();
                var conc = cona.Sum(m => m.id);
            }
            return Content("");
        }

    }

    #region C# 利用反射根据类名创建类的实例对象
    /// <summary>
    /// 反射帮助类
    /// </summary>
    public static class ReflectionHelper
    {
        /// <summary>
        /// 创建对象实例
        /// </summary>
        /// <typeparam name="T"></typeparam>
        /// <param name="fullName">命名空间.类型名</param>
        /// <param name="assemblyName">程序集</param>
        /// <returns></returns>
        public static T CreateInstance<T>(string fullName, string assemblyName)
        {
            string path = fullName + "," + assemblyName;//命名空间.类型名,程序集
            Type o = Type.GetType(path);//加载类型
            object obj = Activator.CreateInstance(o, true);//根据类型创建实例
            return (T)obj;//类型转换并返回
        }

        /// <summary>
        /// 创建对象实例
        /// </summary>
        /// <typeparam name="T">要创建对象的类型</typeparam>
        /// <param name="assemblyName">类型所在程序集名称</param>
        /// <param name="nameSpace">类型所在命名空间</param>
        /// <param name="className">类型名</param>
        /// <returns></returns>
        public static T CreateInstance<T>(string assemblyName, string nameSpace, string className)
        {
            try
            {
                string fullName = nameSpace + "." + className;//命名空间.类型名
                //此为第一种写法
                object ect = Assembly.Load(assemblyName).CreateInstance(fullName);//加载程序集，创建程序集里面的 命名空间.类型名 实例
                return (T)ect;//类型转换并返回
                //下面是第二种写法
                //string path = fullName + "," + assemblyName;//命名空间.类型名,程序集
                //Type o = Type.GetType(path);//加载类型
                //object obj = Activator.CreateInstance(o, true);//根据类型创建实例
                //return (T)obj;//类型转换并返回
            }
            catch
            {
                //发生异常，返回类型的默认值
                return default(T);
            }
        }
    }
    #endregion

}

Mvc5FrameWorkProject/MvcEf5/MvcEf5/Controllers/LoginController.cs
using Models;
using Services.Bll;
using Services.IBll;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc; 

namespace MvcEf5.Controllers
{
    public class LoginController : BaseController
    {
        ILoginServices loginServices;
        public LoginController()
        {
            loginServices = new LoginServices();
        }
        //
        // GET: /Login/
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public JsonResult Index(FormCollection entities)
        {
            Users us = new Users();
            us.username = entities["LoginName"];
            us.userpwd = entities["LoginPassword"];
            var loginresult = loginServices.Loginres(us);
            return Json(new { Success = loginresult.issuccess, Message = loginresult.decription });
        }
	}
}

Mvc5FrameWorkProject/MvcEf5/MvcEf5/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Mvc5FrameWorkProject/MvcEf5/MvcEf5/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Mvc5FrameWorkProject/MvcEf5/MvcEf5/Views/Home/Edit.cshtml
@model Models.Users
@{
    ViewBag.Title = "Edit Page";
    var roles = ViewBag.Roles as List<Models.Roles>;
    var roleslist = ViewBag.RolesList as List<SelectListItem>;
}

<div class="page-container" style="margin-top:100px;">
    <form action="/Home/Edit" method="post">
        <div class="form-body">
            <div class="form-group">
                <label>编号：@(Model.id)</label>
                <input type="hidden" name="id" value="@(Model.id)" />
            </div>
            <div class="form-group">
                <label>姓名</label>
                <div class="input-group">
                    <span class="input-group-addon input-circle-left">
                        <i class="fa fa-envelope"></i>
                    </span>
                    <input type="text" name="username" class="form-control" value="@(Model.username)" placeholder="姓名">
                </div>
            </div>
            <div class="form-group">
                <label>是否停用</label>
                <div class="col-md-12">
                    <div class="mt-checkbox-list">
                        <label class="mt-checkbox mt-checkbox-outline">
                            <input type="checkbox" name="isdelete" class="form-control" @(Model.isdelete ? "checked='checked'" : "")> 停用
                            <span></span>
                        </label>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label>角色</label>
                <div class="input-group">
                    <span class="input-group-addon input-circle-left">
                        <i class="fa fa-envelope"></i>
                    </span>
                    @Html.DropDownList("roleid", roleslist, new { @class = "form-control" })
                </div>
            </div>
        </div>
        <div class="form-actions">
            <button type="submit" class="btn blue">保存</button>
            <a href="/Home/Index" class="btn default">取消</a>
        </div>
    </form>
</div>

Mvc5FrameWorkProject/MvcEf5/MvcEf5/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="@Url.Action("Index","Demo")" class="btn btn-primary btn-large">Go to Lists &raquo;</a></p>
    <p><a href="@Url.Action("Index","Wechat",new {Area="Mobile"})" class="btn btn-primary btn-large">Go to Mobiles &raquo;</a></p>
    <p><a href="@Url.Action("Index","Login")" class="btn btn-primary btn-large">Go to Mobiles &raquo;</a></p>
    <p><a href="@Url.Action("Clear","Home")" class="btn btn-primary btn-large">Clear &raquo;</a></p>
    <p><a href="@Url.Action("Index", "MainMaster", new { area = "Master" })" class="btn btn-primary btn-large">Go Mater &raquo;</a></p>

</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

<div class="row">
    <table class="table">
        <thead class="table-hover">
            <tr>
                <td>编号</td>
                <td>姓名</td>
                <td>是否删除</td>
                <td>类别</td>
                <td>操作</td>
            </tr>
        </thead>
        <tbody class="tab-content">
            @if (Model != null || true)
            {
                foreach (var item in Model as List<Models.Users>)
                {
                    <tr>
                        <td>@item.userid</td>
                        <td>@item.username</td>
                        <td>@item.isdelete</td>
                        <td>@item.roleid</td>
                        <td><a href="/Home/Edit?N=1&&id=@(item.userid)" class="button">编辑</a><a href="/Home/CommonDel?N=1&&id=@(item.userid)" class="button">删除</a></td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>